language: ruby

before_install:
  - gem i rubygems-update -v '<3' && update_rubygems
  - gem install bundler

cache: bundler

env:
  - DB=sqlite3
  - DB=mysql
  - DB=postgresql

rvm:
  - 2.6.3
  - 2.5.5
  - 2.4.6
  - 2.3.8
  - 2.2.10

gemfile:
  - gemfiles/rails_52.gemfile
  - gemfiles/rails_51.gemfile
  - gemfiles/rails_50.gemfile
  - gemfiles/rails_42.gemfile

sudo: false

matrix:
  include:
    - rvm: 2.6.3
      gemfile: gemfiles/rails_edge.gemfile
      env: DB=sqlite3
    - rvm: 2.3.8
      gemfile: gemfiles/rails_41.gemfile
      env: DB=sqlite3
    - rvm: 2.3.8
      gemfile: gemfiles/rails_40.gemfile
      env: DB=sqlite3
    - rvm: 2.1.10
      gemfile: gemfiles/rails_42.gemfile
      env: DB=sqlite3
    - rvm: 2.0.0
      gemfile: gemfiles/rails_42.gemfile
      env: DB=sqlite3
  exclude:
    - rvm: 2.6.3
      gemfile: gemfiles/rails_42.gemfile

  allow_failures:
    - gemfile: gemfiles/rails_edge.gemfile
