language: ruby

before_install:
  - gem update --system
  - gem install bundler

cache: bundler

env:
  - DB=sqlite3
  - DB=mysql
  - DB=postgresql

rvm:
  - 2.5.3
  - 2.4.5
  - 2.3.8
  - 2.2.10

gemfile:
  - gemfiles/rails_52.gemfile
  - gemfiles/rails_51.gemfile
  - gemfiles/rails_50.gemfile
  - gemfiles/rails_42.gemfile

sudo: false

matrix:
  include:
    - rvm: 2.5.3
      gemfile: gemfiles/rails_edge.gemfile
      env: DB=sqlite3
    - rvm: 2.3.8
      gemfile: gemfiles/rails_41.gemfile
      env: DB=sqlite3
    - rvm: 2.3.8
      gemfile: gemfiles/rails_40.gemfile
      env: DB=sqlite3
    - rvm: 2.1.10
      gemfile: gemfiles/rails_42.gemfile
      env: DB=sqlite3
    - rvm: 2.0.0
      gemfile: gemfiles/rails_42.gemfile
      env: DB=sqlite3

  allow_failures:
    - gemfile: gemfiles/rails_edge.gemfile
